# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build 
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Install Nuget Tool'

    - task: NuGetCommand@2
      displayName: 'NuGet Restore'
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      displayName: 'Build .NET Core Solution'
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
      
    - task: DotNetCoreCLI@2
      displayName: 'Unit Test the Code'
      inputs:
        command: test
        projects: '**/*Test/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish the Artifact'
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: DeployDev
  displayName: 'Deploy to DEV Stage'
  dependsOn: Build
  jobs:  
  - deployment: DeployDEV
    environment: DEV
    displayName: 'Deploy Dev Job'
    strategy:
     runOnce:
       deploy:
        steps:        
        - task: AzureRmWebAppDeployment@4
          displayName: 'Deploy to WebApp in Azure'
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Free Trial(b0891bcd-fb7a-4ff9-881e-ff6e91339c70)'
            appType: 'webApp'
            WebAppName: 'modernquote'
            packageForLinux: '$(Pipeline.Workspace)/**/*.zip'

- stage: DeployQA
  displayName: 'Deploy to QA Stage'
  dependsOn: DeployDev
  jobs:
  - deployment: DeployQA
    environment: QA  
    displayName: 'Deploy QA Job'
    strategy:
     runOnce:
       deploy:
        steps:
        
        - task: AzureRmWebAppDeployment@4
          displayName: 'Deploy to WebApp in Azure'
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Free Trial(b0891bcd-fb7a-4ff9-881e-ff6e91339c70)'
            appType: 'webApp'
            WebAppName: 'modernquote-qa'
            packageForLinux: '$(Pipeline.Workspace)/**/*.zip'

