# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore './ModernQuote.Api/ModernQuote.Api/ModernQuote.Api.csproj
    - name: Build
      run: dotnet build './ModernQuote.Api/ModernQuote.Api/ModernQuote.Api.csproj
    - name: Test
      run: dotnet test './ModernQuote.Api/ModernQuote.Api.Test/ModernQuote.Api.Test.csproj
