#Note: Azure DevOps strategy>runOnce does not have an equivalent in GitHub Actions yet, and only the deploy steps are transferred to steps
#Note: the 'AZURE_SP' secret is required to be added into GitHub Secrets. See this blog post for details: https://samlearnsazure.blog/2019/12/13/github-actions/
#Note: Azure DevOps strategy>runOnce does not have an equivalent in GitHub Actions yet, and only the deploy steps are transferred to steps
#Note: the 'AZURE_SP' secret is required to be added into GitHub Secrets. See this blog post for details: https://samlearnsazure.blog/2019/12/13/github-actions/
on:
  push:
    branches:
    - master
env:
  solution: 'ModernQuote.Api/ModernQuote.Api.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: Release
jobs:
  Build_Stage_Build:
    runs-on: windows-latest
    name: Build Job
    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Package Restore
      run: dotnet restore -s {{env.solution}}
    - name: Build with dotnet
      run: dotnet build --configuration Release -s {{env.solution}}
    - name: Test dotnet 
      run: dotnet test -s {{env.solution}}
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/quotemgmt
    - name: Publish the Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ env.DOTNET_ROOT }}
  DeployDev_Stage_DeployDEV:
    # 'Note: Azure DevOps strategy>runOnce does not have an equivalent in GitHub Actions yet, and only the deploy steps are transferred to steps'
    runs-on: windows-latest
    name: Deploy Dev Job
    needs:
    - Build_Stage_Build
    environment:
      name: DEV
    steps:
    - # "Note: the 'AZURE_SP' secret is required to be added into GitHub Secrets. See this blog post for details: https://samlearnsazure.blog/2019/12/13/github-actions/"
      name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    - name: Deploy to WebApp in Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: modernquote
        package: ${{ env.Pipeline.Workspace }}/**/*.zip
  DeployQA_Stage_DeployQA:
    # 'Note: Azure DevOps strategy>runOnce does not have an equivalent in GitHub Actions yet, and only the deploy steps are transferred to steps'
    runs-on: windows-latest
    name: Deploy QA Job
    needs:
    - DeployDev_Stage_DeployDEV
    environment:
      name: QA
    steps:
    - # "Note: the 'AZURE_SP' secret is required to be added into GitHub Secrets. See this blog post for details: https://samlearnsazure.blog/2019/12/13/github-actions/"
      name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    - name: Deploy to WebApp in Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: modernquote-qa
        package: ${{ env.Pipeline.Workspace }}/**/*.zip
                    
